version: '2'
services:
  gateway:
      build: ./gateway
      image: api_gateway/gateway
      container_name: api_gateway_dev
      mem_limit: 1024m
      cpu_shares: '0.5'
      env_file: .env
      ports:
            - "0:8085:8085"