version: '2'
services:
  gateway:
      build: ./gateway
      image: api_gateway/gateway
      container_name: api_gateway_dev
      mem_limit: 1024m
      env_file: .env
      ports:
            - "0:9090:80"
            - "0:9091:443"