version: '2'
services:
  gateway:
      build: ./gateway
      image: api_gateway/gateway
      container_name: api_gateway_dev
      mem_limit: 1024m
      env_file: .env

  nginx:
        build:
              context:
                ./nginx
              args:
                SERVER_NAME: $SERVER_NAME
        container_name: apiGateway-proxy
        ports:
          - 80:80
        volumes:
              - /var/run/docker.sock:/tmp/docker.sock:ro
        depends_on:
         - gateway
